language: php

php:
  - 7.3
  - 7.4
  - 8.0

matrix:
  allow_failures:
    - php: 8.0

install:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --prefer-source --no-interaction

script: vendor/bin/phpspec run ${PHPSPEC_FLAGS}

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover build/coverage.xml; fi
